import esbuild from "esbuild";
import process from "process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian"],
  format: "iife",
  globalName: "FlowUsLimbicPlugin",
  target: "es2016",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  // 确保axios被正确打包
  resolveExtensions: ['.ts', '.js'],
  define: {
    'process.env.NODE_ENV': '"production"',
  },
};

// 只在非生产模式下添加watch选项
if (!prod) {
  buildOptions.watch = true;
}

esbuild
  .build(buildOptions)
  .catch(() => process.exit(1));