/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

// 直接使用全局的obsidian对象
class FlowUsLimbicPlugin extends obsidian.Plugin {
  async onload() {
    console.log('FlowUs Limbic plugin loaded');
    
    // 添加一个测试命令
    this.addCommand({
      id: 'test-command',
      name: '测试命令',
      callback: () => {
        new obsidian.Notice('插件加载成功！');
      }
    });
  }

  onunload() {
    console.log('FlowUs Limbic plugin unloaded');
  }
}

// 导出插件
if (typeof module !== 'undefined' && module.exports) {
  module.exports = FlowUsLimbicPlugin;
} else if (typeof window !== 'undefined') {
  window.FlowUsLimbicPlugin = FlowUsLimbicPlugin;
}